import { invoke } from '@tauri-apps/api/core'
import { listen, type UnlistenFn } from '@tauri-apps/api/event'
import type { ToolName } from '@api/tooling'

/**
 * TypeScript mirror of `install::EVENT_LOG` payload — one line of winget
 * stdout or stderr. Streamed in real time as winget flushes each line.
 */
export interface InstallLogEvent {
  install_id: string
  stream: 'stdout' | 'stderr'
  line: string
}

/**
 * TypeScript mirror of `install::EVENT_DONE` payload. `cancelled` is true
 * only when the user explicitly cancelled — distinct from `success: false`
 * caused by winget returning a non-zero exit on its own.
 */
export interface InstallDoneEvent {
  install_id: string
  exit_code: number | null
  success: boolean
  cancelled: boolean
  error: string | null
}

/**
 * Probe whether `winget` itself is on PATH. Frontend uses the result to
 * decide between the install button and the "Mở trang tải" + "Tôi đã cài"
 * manual fallback (Win 10 pre-1809 / restricted enterprise machines).
 */
export async function wingetAvailable(): Promise<boolean> {
  return invoke<boolean>('winget_available')
}

/**
 * Kick off a winget install for `tool`. Returns as soon as the child
 * process is spawned; progress streams via {@link onInstallLog} events and
 * completion via {@link onInstallDone}.
 *
 * `installId` is generated by the caller (a uuid-ish string is fine) so log
 * lines and the done payload can be correlated with the originating click.
 */
export async function toolInstallStart(installId: string, tool: ToolName): Promise<void> {
  return invoke<void>('tool_install_start', { installId, tool })
}

/**
 * Cancel a running install — the backend kills the winget child process
 * and emits a `done` event with `cancelled: true`.
 */
export async function toolInstallCancel(installId: string): Promise<void> {
  return invoke<void>('tool_install_cancel', { installId })
}

/**
 * Subscribe to per-line log events from any in-flight install. Filter by
 * `install_id` on the handler side — the backend emits a single event
 * stream for all installs (there is at most one at a time today, but the
 * payload carries the id so multi-install UI is forward-compatible).
 *
 * Returns the unlisten function — call it on owner cleanup to avoid
 * leaking subscriptions across hot reloads.
 */
export async function onInstallLog(
  handler: (event: InstallLogEvent) => void
): Promise<UnlistenFn> {
  return listen<InstallLogEvent>('tool-install-log', event => handler(event.payload))
}

/**
 * Subscribe to install-done events. Fires once per install (success,
 * failure, or cancellation). Use the same filter-by-id pattern as
 * {@link onInstallLog}.
 */
export async function onInstallDone(
  handler: (event: InstallDoneEvent) => void
): Promise<UnlistenFn> {
  return listen<InstallDoneEvent>('tool-install-done', event => handler(event.payload))
}
